spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Deslej/microservices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        # native:
        # search-locations: "file:///D://config"
        # search-locations: "classpath:/config"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071

